apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-b-metrics
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: team-b
    server: https://kubernetes.default.svc
  project: observability
  source:
    path: tenants/team-b
    repoURL: https://github.com/bpschmitt/otel-argo
    targetRevision: app-of-apps
  syncPolicy:
    automated:
      enabled : true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true