apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: otel-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: otel-root/children
    repoURL: https://github.com/bpschmitt/otel-argo
    targetRevision: app-of-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true