# Kustomize Base for OpenTelemetry Operator.
# This file is pure Kustomize and relies on pre-rendered YAML manifests.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The base only includes the pre-rendered Helm output (manifests.yaml).
resources:
- manifests.yaml

# Set common labels to be inherited by all resources in this base
commonLabels:
  app.kubernetes.io/name: otel-operator
  app.kubernetes.io/part-of: opentelemetry
  kustomize.component: otel-operator-base