apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-operator
      targetRevision: 0.97.1
      helm:
        releaseName: opentelemetry-operator
        valueFiles:
          - $values/components/otel-operator/values.yaml
    - repoURL: https://github.com/bpschmitt/otel-argo
      targetRevision: app-of-apps
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: otel-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true