kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opentelemetry-targetallocator-clusterrolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentelemetry-target-allocator-clusterrole
subjects:
- kind: ServiceAccount
  name: opentelemetry-target-allocator-serviceaccount
  namespace: otel-system