---
# Source: nr-k8s-otel-collector/charts/kube-state-metrics/templates/stsdiscovery-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stsdiscovery-nr-k8s-otel-collector-kube-state-metrics
  namespace: otel-system
  labels:    
    helm.sh/chart: kube-state-metrics-5.30.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: kube-state-metrics
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/instance: nr-k8s-otel-collector
    app.kubernetes.io/version: "2.15.0"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resourceNames:
  - nr-k8s-otel-collector-kube-state-metrics
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch